{{- if and .Values.persistence.enabled ( not .Values.useStatefulSet) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "appsmith.fullname" . }}
  namespace: {{ include "appsmith.namespace" . }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  storageClassName: efs-pv
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}